### PR TITLE
update to 1.12.98 and fixing the log10 plot problem in xy_graph

### PR DESCRIPTION
**Pull request by jrcoding**
1.12.85 has still a problem with log10 plot and xy_graph

We decided not to fix it in 1.12.85 (because it needs changes at several locations ) but doing an update to 1.12.98 together with fixing the log10 plot problem because it´s better locatable in 1.12.98

### CODE REVIEW

**Comment by ralphlange** [comment]
What's the status of pushing the log10/x-y-plot changes upstream?

**Comment by mdavidsaver** [comment]
Joachim, can you confirm the SHA1 hash and size of edm_1.12.98.orig.tar.gz?  I've become distrustful of pristine-tar.  If these don't match then please email me the file you built with.

> 48fb74404f57b903022089aa281ecc6b0ecbb2fb  2783737  edm_1.12.98.orig.tar.gz

**Comment by mdavidsaver** [comment]
I'm going to accept these changes although the merge did lose some of my source changes.  To keep this from happening in future I'm working to convert this package to source format "3.0 (quilt)".

**Comment by jrcoding** [comment]
Michael, seems to be o.k. (see attached the output of sha1sum and ls)

> sha1sum edm_1.12.98.orig.tar.gz                                                               1
48fb74404f57b903022089aa281ecc6b0ecbb2fb edm_1.12.98.orig.tar.gz

> ls -l edm_1.12.98.orig.tgz
-rw-rw-r-- 1 owner owner 2783737 Jan 26 09:01 edm_1.12.98.orig.tgz

**Pull request merged**
